require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

task :default => :spec

namespace :pdf_create do
    task :build do
        system "rake build && rake"
    end
end